services:
  - type: web
    name: rag-assistant
    env: docker
    plan: free
    dockerCommand: uvicorn app.api:app --host 0.0.0.0 --port 10000
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: ENABLE_WEB_UI
        value: "true"
      - key: OPENAI_API_KEY
        sync: false
      - key: VECTOR_TOP_K
        value: "3"
      - key: USE_FAISS
        value: "auto"
